#!/usr/bin/env bash
# A script that will display information about subdomains.
function subdomain_info {
  record=$(dig +short "$1.$2")
  if [[ -n "$record" ]]; then
    record_type=$(dig "$1.$2" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
    echo "The subdomain $1 is a $record_type record and points to $record"
  else
    echo "The subdomain $1 does not exist"
  fi
}

domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
  subdomains=("www" "lb-01" "web-01" "web-02")
else
  subdomains=($subdomain)
fi

for sub in "${subdomains[@]}"; do
  subdomain_info $sub $domain
done
