#!/usr/bin/env bash
# A script that transfers a file from our client to a server:
if [ $# -ne 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

path="$1"
ip="$2"
username="$3"
ssh_path="$4"

scp -o StrictHostKeyChecking=no -i "$ssh_path" "$path" "$username@$ip:~/"
