#!/usr/bin/env bash
# Install Nginx on web-01

apt update
apt install nginx -y
ufw allow 'Nginx HTTP'
mkdir /var/www/html
chmod -R 755 /var/www
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
service nginx restart
