#!/usr/bin/env bash
# Install Nginx on web-01

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
mkdir /var/www/html
chmod -R 755 /var/www
sudo touch /var/www/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
sudo sed -i '53i\rewrite ^/redirect_me http://bachmanity.tech permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
