#!/usr/bin/env bash
# Install Nginx on web-01

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
mkdir /var/www/html
chmod -R 755 /var/www
sudo touch /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo service nginx start
sudo sed -i '54i\error_page 404 /404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
