#!/usr/bin/env bash
# Install Nginx on web-02
# shellcheck disable=SC2154

sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
mkdir /var/www/html
chmod -R 755 /var/www
sudo touch /var/www/html/index.html
sudo touch /var/www/html/404.html
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo service nginx start
sudo sed -i '54i\rewrite ^/redirect_me http://bachmanity.tech permanent;' /etc/nginx/sites-enabled/default
sudo sed -i '55i\error_page 404 /404.html;' /etc/nginx/sites-enabled/default
sudo sed -i "16i\add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
