#!/usr/bin/env bash
# A script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -uroot -p"$1" --all-databases -rbackup.sql
tar -cvzf "$(date +%m-%d-%Y).tar.gz" ./backup.sql
