#!/usr/bin/env bash
# Nginx must be running, and listening on port 80
sudo fuser -k 80/tcp
sudo sed -i 's/listen 80;/listen 80 default_server;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen [::]:80;/listen [::]:80 default_server;/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
