#!/usr/bin/env bash
# Nginx must be running, and listening on port 80
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx start
