#!/usr/bin/env bash
# Make your fix short and sweet.
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
