#!/usr/bin/env bash
# manages manage_my_process.
# shellcheck disable=SC2046
# Requirements:

# When passing the argument start:
# Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process started
# When passing the argument stop:
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Displays manage_my_process stopped
# When passing the argument restart
# Stops manage_my_process
# Deletes the file /var/run/my_process.pid
# Starts manage_my_process
# Creates a file containing its PID in /var/run/my_process.pid
# Displays manage_my_process restarted
# Displays Usage: manage_my_process {start|stop|restart} if any other argument or no argument is passed

PID_FILE="/var/run/my_process.pid"

start() {
    ./manage_my_process &
    echo $$ > "$PID_FILE"
}

stop() {
    rm "$PID_FILE"
    pkill -of manage_my_process
}

restart() {
    stop
    start
}

exec_commands(){
    case "$ARGV" in
        start)
            start
            echo "manage_my_process started."
            ;;
        stop)
            stop
            echo "manage_my_process stopped."
            ;;
        restart)
            restart
            echo "manage_my_process restarted."
            ;;
        *)
            ;;
    esac
}

if [ $# -gt 0 ]; then
    ARGV="$1"
    exec_commands
else
    echo "Usage: manage_your_process {start|stop|restart}"
fi


