#!/usr/bin/env bash
# displays the PID, along with the process name, of processes whose name contain the word bash.
# shellcheck disable=SC2009

pgrep -f bash | xargs -I{} sh -c 'echo {} $(ps -p {} -o comm=)'
