#!/usr/bin/env bash
# stops 4-to_infinity_and_beyond process.
# shellcheck disable=SC2009


PID=$(ps aux | grep '4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')

if [[ -z $PID ]]; then
  echo "4-to_infinity_and_beyond is not running"
else
  pkill -TERM -P "$PID"
fi
