#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and displays this data.

awk '{print $1" "$9}' apache-access.log | sort | uniq -c | awk '{print $1" "$2" "$3}' | sort -rn | awk '{print "    "$1" "$2" "$3}' | head -n 10
