#!/usr/bin/env bash
# displays the visitor IP along with the HTTP status code from the Apache log file.

#!/bin/bash

awk '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | awk '{ printf("%-15s %-10s %-10s\n", $1, $2, $3) }' | sort -nr
