#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and displays this data.

awk '{ print $1 " " $9 }' apache-access.log | sort | uniq -c | awk '{ printf("    %-10s %-10s\n", $2, $3) }' | sort -nr
