#!/usr/bin/env bash
# display hrs from 0 to 12
# display mins from 1 to 59

hr=0
while [ $hr -lt 12 ]
do
    echo "Hour: " $hr
    min=1
    while [ $min -lt 60 ]
    do
        printf "%02d\n" $min
        min=$((min+1))
    done
    hr=$((hr+1))
done
