#!/usr/bin/env bash
# displays:
# The content of the current directory
# In a list format
# Where only the part of the f after the first dash is displayed (refer to the example)

for file in $(ls -p | grep -v /)
do
    f=$(echo $file | cut -d '-' -f2-)
    echo $f
done
