#!/usr/bin/env bash
# A script that run the whoami command under the user passed as an argument
if [ $# -ne 1 ]; then
    echo "Usage: $0 <username>"
    exit 1
fi

USERNAME=$1

sudo -u "$USERNAME" whoami
